### PR TITLE
Added compatibility for newer Xcode (until v6.3-beta) and updated the UI

### PR DESCRIPTION
**Pull request by sh4nji**
I added support for Xcode 6.1 and updated the UI a bit to integrate better with Yosemite.

Tested on Yosemite.

### CODE REVIEW

**Comment by orta** [comment]
would love this merged, and 6.2 support

**Comment by orta** [comment]
I submitted a PR to @sh4nji for 6.2

**Comment by sh4nji** [comment]
Doesn't seem like there is much activity here anymore.

**Comment by edwardaux** [comment]
Sorry @sh4nji ... I don't know why I didn't see this pull request earlier. My apologies.

**Pull request merged**
